### ISSUE TITLE
[BUG] Nginx와 streamlit 통신 관련 에러

### ISSUE THREAD

**Issue by C7C4FF** [boostcampaitech6/level2-3-nlp-finalproject-nlp-02#23]
## Describe the bug

```
WebSocketConnection WebSocket onerror
WebSocket connection to 'ws://mopic.today/_stcore/stream' failed
```

에러 발생하여 app.py 화면이 정상적으로 띄워지지 않는 현상 발견

## To Reproduce

```
import streamlit as st

st.title("MOPIc")
```
아주 간결한 코드여도 에러 발생. 
Nginx 컨픽은 아래와 같았음

**Comment by C7C4FF** [comment]
```
server {
    listen 80;
    server_name mopic.today;

    location /api/ {
        proxy_pass;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        proxy_pass;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /_stcore/health {
        proxy_pass/_stcore/health;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /_stcore/stream {
        proxy_pass;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 86400;
    }
}
```

많은 시도 끝에... Streamlit에서 웹 소캣 요청하는데 이게 문제였던 것 같습니다...
Nginx 컨픽을 위와 같이 변경해주니 해결했습니다.

제법 오래 헤맸지만, 잊기 전에 이슈 올려봅니다...

**Comment by valofosho** [comment]
> ```
> server {
>     listen 80;
>     server_name mopic.today;
> 
>     location /api/ {
>         proxy_pass;
>         proxy_set_header Host $host;
>         proxy_set_header X-Real-IP $remote_addr;
>         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>         proxy_set_header X-Forwarded-Proto $scheme;
>     }
> 
>     location / {
>         proxy_pass;
>         proxy_set_header Host $host;
>         proxy_set_header X-Real-IP $remote_addr;
>         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>         proxy_set_header X-Forwarded-Proto $scheme;
>     }
> 
>     location /_stcore/health {
>         proxy_pass;
>         proxy_set_header Host $host;
>         proxy_set_header X-Real-IP $remote_addr;
>         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>         proxy_set_header X-Forwarded-Proto $scheme;
>     }
> 
>     location /_stcore/stream {
>         proxy_pass /_stcore/stream;
>         proxy_http_version 1.1;
>         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>         proxy_set_header Host $host;
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header Connection "upgrade";
>         proxy_read_timeout 86400;
>     }
> }
> ```
> 
> 많은 시도 끝에... Streamlit에서 웹 소캣 요청하는데 이게 문제였던 것 같습니다... Nginx 컨픽을 위와 같이 변경해주니 해결했습니다.
> 
> 제법 오래 헤맸지만, 잊기 전에 이슈 올려봅니다...

오 고생하셨습니다 이슈 참고 해서 진행할게욥!!
