### ISSUE TITLE
[FEAT] catboost scoring 모델 추가

### ISSUE THREAD

**Issue by valofosho** [boostcampaitech6/level2-3-nlp-finalproject-nlp-02#65]
## Background

모델 output을 기준으로 유저의 예상 등급을 반환
## To do 

- [x] score/catboost 브랜치 생성
- [x] 모델 load 후 dataframe 형태로 question 테이블 형성
- [x] label mapping
- [x] score table에 업로드

**Comment by valofosho** [comment]
기존 ai hub 데이터를 활용하는 과정에서 label mapping이 한 문제당 되어 있어서 
실제 값을 추론하는 과정에서도 하나의 문제 당 하나의 라벨이 나오도록 설정한 뒤에
세 문제에 대한 라벨을 후에 평균내어 하는 방향으로 우선 진행 중입니다!!!!!

**Comment by C7C4FF** [comment]
앗 좋습니다~ 저희도 inference로 들어가는 건 각 문제니까 그렇게 하는 게 맞아보여요!! 짱.

**Comment by C7C4FF** [comment]
헉 이제 보니까 test_router에서 진행 중이시네요.

제가 방금 리팩토링 끝냈는데.. 혹시 한번 봐주시고 변경된 코드에서 진행해주실 수 있을까요?

**Comment by valofosho** [comment]
> 헉 이제 보니까 test_router에서 진행 중이시네요.
> 
> 제가 방금 리팩토링 끝냈는데.. 혹시 한번 봐주시고 변경된 코드에서 진행해주실 수 있을까요?

앗 넵넵 제가 밖에 나와서 이따 저녁 늦게 들어가서 작업할 때 바꿔서 작업하겠습니다!!
 리팩토링 고생하셨습니다!!짱짱~
